### ISSUE TITLE
Issues with Geometry

### ISSUE THREAD

**Issue by ypnos** [paceholder/nodeeditor#108]
I don't fully understand what is going on with the scene geometry. For example, if (in the flow view) I want to place a node's center under the mouse cursor:

```c++
auto pos = this->mapToScene(event->pos());
auto shift = _scene->getNodeSize(node) / 2.f;
pos = {pos.x() - shift.width(), pos.y() - shift.height()};
_scene->setNodePosition(node, pos);
```

This works correctly. However, with this code, nodes are off:
```c++
auto pos = this->mapToScene(event->pos());
auto shift = node.nodeGraphicsObject().boundingRect().size() / 2.f; // wrong?
pos = {pos.x() - shift.width(), pos.y() - shift.height()};
_scene->setNodePosition(node, pos);
```

Similarly, if I do something like this:
```c++
fitInView(scene()->itemsBoundingRect(), Qt::KeepAspectRatio);
```

I would expect all nodes to fit in the view nicely. Instead, the zoom is too strong and also the view is somewhat displaced. Why does the QGraphicsScene get the bounding rectangle wrong?

**Comment by kPanesar** [comment]
The fitInView bug might be related to [this](https://github.com/paceholder/nodeeditor/pull/104) pull request I made a while back to fix an issue with the [scene locking up](https://github.com/paceholder/nodeeditor/issues/79). The fix for that was to set the scene rectangle according to the mouse movement .
```cpp
setSceneRect(sceneRect().translated(difference.x(), difference.y()));
```
I also need a way to fit the entire node graph in view but am facing the same issue as you where the items are displaced by a certain amount. The problem gets worse when you're loading different node graphs in the same scene and happen to drag the scene in between. For some reason setting the scene rect seems to have an effect on the items bounding rect. Not sure why.
