### ISSUE TITLE
create modules with factory pattern

### ISSUE THREAD

**Issue by abdolahsa** [paceholder/nodeeditor#130]
when you register models you create an instance of them and when needed you clone them. why you not just create them when needed? you can save all of the formats in a factory class and when needed create an instance of them by using factory and their creator functions! suppose you have tens of models and each take memory so when you create them all it causes memory consumption.

**Comment by russelltg** [comment]
My thought when I added that was so you can have different models based on the data in a class and not the class itself to allow for models to be created that aren't known at compile time.

However, the same effect could be made if the creators were stored in

**Comment by abdolahsa** [comment]
In my application I've many blocks which for some blocks takes some time to be initialized. see [here ](https://en.wikipedia.org/wiki/Lazy_initialization)and [here](https://en.wikipedia.org/wiki/Lazy_evaluation), using factory method to create objects when needed has several benefits, We don’t incur the overhead of construction unless we actually use the object, and our startup times can be faster as a result (initialization of all blocks may takes long time). so we must separate registration from object creation.

**Comment by facontidavide** [comment]
I just created a pull request that is related to this issue #135

**Comment by Malcohol** [comment]
Hi all (and especially @facontidavide).

Change #164, which is closely related to this issue, has caused my application to break. 

I'd like to state that I'm definitely sympathetic with the design direction that that PR implies, and rather than any kind of retreat, I'd prefer nodeeditor to move further towards explicit factories.

I had menu entries that, when selected, opened an open file dialog so that the node contents could be populated from the data in a file. These were awkward to implement in the prototype-based clone approach which existed prior to #164 because I had to pretend that my factory was actually an instance of a node data model. This was silly because it really only provided a name and a clone method. The clone method, once a file was selected, would return a genuine instance of the class to instantiate in the flow scene. Nevertheless, the approach worked.

After #164, I can't logically distinguish between the factory method being called to query its name, or being called to add its objects to the scene. Neither can I can't use the static method option, because the set of factories in my application is itself populated from another registry. 

Right now, I'm going to have to use a hacky workaround where I assume that operator() will be called exactly once to populate the menus. This is obviously brittle :'(

In the PR discussion for #164, the following design was proposed, but not adopted:

class NodeDataModelSpec {
public:
    // Actually create the NodeDataModel
    virtual std::unique_ptr<NodeDataModel> create() const = 0;
    // Other information about the specific kind of NodeDataModel
    virtual QString name() const = 0;
    // ...
};

That looks ideal. Would there be support for switching to such a design? If not, can anyone suggest how to support my use-case?

Thanks for any thoughts on this :)
