### ISSUE TITLE
Embedded widget leaking

### ISSUE THREAD

**Issue by Daguerreo** [paceholder/nodeeditor#271]
Embedded widgets are leaking according to Valgrind.

This is the report for the image example, adding both nodes to the scene and then closing the application

![leak](https://user-images.githubusercontent.com/6747152/93316022-fc555180-f80b-11ea-9219-009304187ed0.png)

this should be the same of #248

**Comment by skarnproject** [comment]
This is most likely caused by the way the embedded widget is created. If it is created with new and has no parent, there is no way for it to destroy itself when the node is removed / application closed. deleting in explicitly in the destructor should help.

**Comment by Daguerreo** [comment]
I figured out. 

Models are always created when registerModels() is called, before actually being created or showed, and then when a node is placed to the scene.This cause the node placed to have the embedded widget correctly deleted because parent is assigned, but their istance during the registerModels() does not have parent and then leak. But calling a delete if parent is setted is not correct anyway causing a crash when exiting the program.

The correct behaviour (for image example here) is:

```
ImageShowModel::~ImageShowModel()
{
    if(_label && !_label->parent())
        _label->deleteLater();
}
```

**Comment by Daguerreo** [comment]
Sadly, that one wasn't the perfect solution, since reloading a scene would fall in a segfault anyway. I just moved the creation of the embedded widget the first time embeddedWidget() is called. However checking it for nullptr would create it, so in a condition like this one should manually delete the widget to avoid memory leaking.

**Comment by paceholder** [comment]
Qt docs  state:

`QGraphicsProxyWidget shares ownership with [QWidget](https://doc.qt.io/qt-6/qwidget.html), so if either of the two widgets are destroyed, the other widget will be automatically destroyed as well.`

It might happen that a model is initialized shortly in order to call `model->name()` when building a registry.
It is suggested in the comment I just added to the code to create the embedded widget in-place with a lazy initialization when the user is actually embedding the widget into a node and is calling `Model::embeddedWidget()`

This problem will be addressed properly in the vertsion 3.
