### ISSUE TITLE
Drag and drop flow file

### ISSUE THREAD

**Issue by yvanblanchard** [paceholder/nodeeditor#406]
Hello

I would like to drag and drop a saved flow file for loading it (instead of selecting it from load menu, as for the calculator example).
I was able to build the Canvas widget (nodes editor) in a dialog in order to set and enable the drops, but the drop seems to work only for the main dialog (top menus of main dialog) but not for the central canvas widget.
Any help?

thank you.

**Comment by yvanblanchard** [comment]
Problem solved.
Just have to set 'setAcceptDrops(true)' in the GraphicsView class constructor, and implement 'dragEnterEvent' (see Qt help/examples for details).

**Comment by PabloPicose** [comment]
How do you manage drag and drop for Nodes? because I dont like the right-click build-in contextual menu. I prefer place some list widget or other storage widget, I enabled the setAcceptDrops on the QtNodes::GraphicsView, but I dont found how can I place any defined Node in the registry and place in the 'drop' position without overload the QtNodes::GraphicsView class and reimplement some functionality. Thanks!
