### ISSUE TITLE
May I ask, how do I add a flow control pin to a node? (Like the blueprints for Unreal Engine)

### ISSUE THREAD

**Issue by 2822907581** [paceholder/nodeeditor#432]
This is a masterpiece! But may I ask, 
> How do I add the pins used to control the flow of the program? (Just like the blueprints for the Unreal Engine)
> I plan to add nodes with functions like For, If, Switch, etc., but only if there are pins for controlling the flow.
Thanks for all your efforts.

**Comment by AriyaConseils** [comment]
You can control the flow in many ways. First, you need to create a node that will handle the incoming data. Once the data is received, you can perform your operations and then trigger the outgoing data.

**Comment by 2822907581** [comment]
> You can control the flow in many ways. First, you need to create a node that will handle the incoming data. Once the data is received, you can perform your operations and then trigger the outgoing data.

Thank you for your reply. XD
I understand that through the node, it is possible to do some processing of the input port and pass it to the output port. But the problem I'm having is, I'd like to have a node that acts like ‘IF’. 
For example, when an input port is true, the node connected to the output port ‘Then’ is executed, and vice versa, when it is false, the node connected to the output port ‘Else’ is executed.

**Comment by AriyaConseils** [comment]
In a Qt Node Editor, the design follows a flow-based approach rather than a state-based one. This means that, for a node acting as an IF module, you should implement your condition logic within the setInData function. Each time a new value is received, the condition is evaluated, and based on this evaluation, a boolean result is stored. Following this, you must emit the dataUpdated(PortIndex const index) signal, where the PortIndex value will be 0 if the condition is true, or 1 if false, according to your specific rules. It's crucial that the output is not left as a null pointer; otherwise, the signal will not propagate.

For a practical example and a better understanding of data propagation semantics instead of state-based logic, you can explore the tool available at [www.swiiz.io](http://www.swiiz.io/), which utilizes this library to develop Qt applications.


if you may, you can give me you email i'll send you a class doing an if condition.

**Comment by 2822907581** [comment]
> In a Qt Node Editor, the design follows a flow-based approach rather than a state-based one. This means that, for a node acting as an IF module, you should implement your condition logic within the setInData function. Each time a new value is received, the condition is evaluated, and based on this evaluation, a boolean result is stored. Following this, you must emit the dataUpdated(PortIndex const index) signal, where the PortIndex value will be 0 if the condition is true, or 1 if false, according to your specific rules. It's crucial that the output is not left as a null pointer; otherwise, the signal will not propagate.
> 
> For a practical example and a better understanding of data propagation semantics instead of state-based logic, you can explore the tool available at [www.swiiz.io](http://www.swiiz.io/), which utilizes this library to develop Qt applications.
> 
> if you may, you can give me you email i'll send you a class doing an if condition.

Thank you very much for your kind help! 
My email: AlexWilliamsTechOfficial@gmail.com
( I am a student, and the 'Official' in my email address is given casually. Please don't mind.  XD)
