### ISSUE TITLE
Small graphical bug with connections that are ascending

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#78]
It seems when connections are ascending (like the car is going up a hill in a side-scroller) the top of the right side of the connection line starts to get cut off:

![connbug](https://cloud.githubusercontent.com/assets/7105082/24279619/9b9017e0-1010-11e7-97ee-86f75cb7b164.gif)

**Comment by LandonJerre** [comment]
Both ends are affected, if you look at your example, the line that comes out of the multiply node has a clipped bottom too. I ran into this too when I tried to reimplement connection drawing to use Catmull Rom splines instead of cubic Beziers, it looked like ConnectionGeometry::boundingRect sometimes gave back a slightly smaller rect than necessary. I've never got around fixing this, and eventually dropped the whole spline swapping thing.

**Comment by russelltg** [comment]
Good point, never noticed that!

**Comment by paceholder** [comment]
Should be fixed now.
