### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#79]
The scrolling issue (outlined in the readme) where you have to move nodes to resize the scene is really annoying, and I found a fix for it.
```C++
	mView->setSceneRect(-320000, -320000, 640000, 640000);
	mView->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
	mView->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
```

Just makes the scene huge and turns scrollbars off. Not super clean, but the best way to do it.

http://stackoverflow.com/questions/19207153/how-to-pan-beyond-the-scrollbar-range-in-a-qgraphicsview

**Comment by paceholder** [comment]
That is a reasonable solution. The only thing I concerned with is the cached background image. Would it be of size 64Kx64K if we scroll little bit around? I turn the background cashing on [here](https://github.com/paceholder/nodeeditor/blob/master/src/FlowView.cpp#L46).

I saw another way of fixing it which seems to work: we would re-define various mouse view events and detect there when the mouse button is pressed and when the scene is "dragged". Then, instead of scrolling the scene we just move the scene rectangle according to the mouse traveled distance. 

Well it is better to see the [code](https://github.com/mkeeter/antimony/blob/develop/app/canvas/canvas_view.cpp#L85)
Just search for `setSceneRect` in the file
