### ISSUE TITLE
Allow models with dynamic number of in- and outputs

### ISSUE THREAD

**Issue by paceholder** [paceholder/nodeeditor#94]

**Comment by russelltg** [comment]
Something that I've been thinking about for a while is the usage of a similar thing to Qt's model-view system, but applied to this. There could be a default model that's similar to the current implementation, with node classes etc, but then people could write their own. It'd be very nice for me as I have my own data structure for nodes, and keeping them in sync is a ton of work. 

I'm willing to write it if you're interested. I'll probably write it anyways because keeping them in sync is a pain. This would also help decouple the rendering from the data flow framework because the data flow tools could just be moved into the default model.

**Comment by paceholder** [comment]
Sorry, I do not get how the dynamic models are related to what you are describing

**Comment by russelltg** [comment]
Oh, it'd just be one way to solve it with an interface, that would solve other problems as well. You're right though, it's not directly related. 

I'll open another issue

**Comment by RyouBakura** [comment]
Hey. I have something like this:

```
unsigned int SwitchNode::nPorts(PortType portType) const
{
  unsigned int result = 1;
  switch (portType)
  {
    case PortType::In:
      result = 2;
      break;
    case PortType::Out:
      result = 1 + dynamicNumber + ( rand() % 6 + 1 );
      break;
    default:
      break;
  }
  return result;
}
```

Whenever I place a new node of this type in the scene, it will have a random number of output ports. However if I change the 'dynamicNumber' variable of such an existing node, nothing happens. My vast experience as programmer tells me that I need to notify someone of something.

With the help of QTCreators search, I was able to find that this virtual "nPorts" function is called by "iterateOverNodeDataDependentOrder". However the tracks end there. Could someone give me a clue please?

Kind regards
Bakura

**Comment by navyenzo** [comment]
Did you ever figure out how to get the nodes to show up when you add them after the node's already created?

**Comment by RyouBakura** [comment]
No, sorry. I ended up writing my own node editor in C#.
